name: 'user-service'
services:
  webapp:
    env_file:
      - .env
    build:
      context: .
    depends_on:
      - postgres
    environment:
      MODE: ${MODE}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ISSUER: ${SECRET_ISSUER}
    ports:
      - ${APP_PORT}

  postgres:
    image: 'postgres:17'
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
    ports:
      - ${DB_PORT}
